// Transaction Action Types

// Create
export const INITIATE_TRANSACTION_CREATION = "INITIATE_TRANSACTION_CREATION";
export const TRANSACTION_CREATION_SUCCESSFUL =
  "TRANSACTION_CREATION_SUCCESSFUL";
export const TRANSACTION_CREATION_FAILED = "TRANSACTION_CREATION_FAILED";

// Fetch
export const INITIATE_TRANSACTION_FETCH = "INITIATE_TRANSACTION_FETCH";
export const TRANSACTION_FETCH_SUCCESSFUL = "TRANSACTION_FETCH_SUCCESSFUL";
export const TRANSACTION_FETCH_FAILED = "TRANSACTION_FETCH_FAILED";

// Update
export const INITIATE_TRANSACTION_UPDATE = "INITIATE_TRANSACTION_UPDATE";
export const TRANSACTION_UPDATE_SUCCESSFUL = "TRANSACTION_UPDATE_SUCCESSFUL";
export const TRANSACTION_UPDATE_FAILED = "TRANSACTION_UPDATE_FAILED";

// Delete
export const INITIATE_TRANSACTION_DELETION = "INITIATE_TRANSACTION_DELETION";
export const TRANSACTION_DELETION_SUCCESSFUL =
  "TRANSACTION_DELETION_SUCCESSFUL";
export const TRANSACTION_DELETION_FAILED = "TRANSACTION_DELETION_FAILED";
