// Authentication Action Types

// Create
export const START_ACCOUNT_SIGNUP = "START_ACCOUNT_SIGNUP";
export const ACCOUNT_SIGNUP_SUCCESS = "ACCOUNT_SIGNUP_SUCCESS";
export const ACCOUNT_SIGNUP_FAILURE = "ACCOUNT_SIGNUP_FAILURE";

// Account Details
export const START_FETCH_ACCOUNT_DETAILS = "START_FETCH_ACCOUNT_DETAILS";
export const FETCH_ACCOUNT_DETAILS_SUCCESS = "FETCH_ACCOUNT_DETAILS_SUCCESS";
export const FETCH_ACCOUNT_DETAILS_FAILURE = "FETCH_ACCOUNT_DETAILS_FAILURE";

// Fetch
export const START_FETCH_USER_ACCOUNT = "START_FETCH_USER_ACCOUNT";
export const FETCH_USER_ACCOUNT_SUCCESS = "FETCH_USER_ACCOUNT_SUCCESS";
export const FETCH_USER_ACCOUNT_FAILURE = "FETCH_USER_ACCOUNT_FAILURE";

// Update
export const START_UPDATE_ACCOUNT_INFO = "START_UPDATE_ACCOUNT_INFO";
export const UPDATE_ACCOUNT_INFO_SUCCESS = "UPDATE_ACCOUNT_INFO_SUCCESS";
export const UPDATE_ACCOUNT_INFO_FAILURE = "UPDATE_ACCOUNT_INFO_FAILURE";

// Delete
export const START_DELETE_ACCOUNT = "START_DELETE_ACCOUNT";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_FAILURE = "DELETE_ACCOUNT_FAILURE";
